language: node_js
node_js:
- 10
deploy:
  provider: npm
  email: "betterofsong@gmail.com"
  api_key:
    secure: PtuHwjrOOGyoK+9N/kRKI8ValWeStPFIHKLZarBCeZ0gOMC96sHcejnBjx3O3cXRSFmc0LOdbLXB/iob/e79tlb4qzkEKJ4R7TWq7ZE3Qj8zMu+7LGPiy+S7c3HiO7WPrDViGy0/a1TNasUWo8NOh/RToWoS2DRcRe0WDzq6XoHJTtOc6NB5nN/NRg9E/60+0RyOpc0j/ETCcMQ8ZgUuzTJ1IM+8wMb6fmeX2N6RRGGUwaSDdxb7uDrDuVS/NAh5Jz9fgjGnpUO8WrRKjUyREROySZy3rdjElAEpkqawle/kWCW1Rr/Dz8f1ThpzxNj4V9rkdzaLXu0mohwJFewMvxI3CYYZ9LQ8yz7b6hpcnwFILKsN7cQpY0rkLWpAcnlR+G9y5QiFQXBjfrbDYgurXlCmC+N3Q7n+udJxyb+coRyMZ8QEG5m2UzSI8829+h4vjfxSUDENSBuGbWfGZGT/rF8QllLkCjhaLODC93nFb2FO2SW9gr5mfNl5PUwB5L5AqCMPyW0X1EZGi8yi1FudCHvcaT9xUpyxr8gdEPUPKxNZxbdiBvYxPLYLUZRng1KtW7UVIFUaomDeJIMsbGRcL+VzRhUnVy0jfNuGv2qRfAli2J7NGxeL3AtxmvFyUM/OakH92R+HAGRxw0GZ7dGgRmmh6UGcjZKh2YtQfM74soE=
